#!/usr/bin/env ruby
#
require 'json'
base_dir="#{Dir.home}/.exiom"

provisioner = ARGV[1]
builder = ARGV[0]

prov_path = "#{base_dir}/images/builders/#{builder}.json"

if File.exist? prov_path
  data = JSON.parse(File.open("#{base_dir}/images/provisioners/#{provisioner}.json", "r").read())
  builder = JSON.parse(File.open("#{base_dir}/images/builders/#{builder}.json", "r").read())["builders"]
  data["builders"] = builder

  File.open("#{base_dir}/images/exiom.json", "w") {|f| f.write(JSON.pretty_generate(data)) } 
else
  puts "Builder does not exist"
end